FROM python:3.12.5-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY apps/worker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY apps/worker .
COPY scientific/ /app/scientific/

EXPOSE 8080

CMD ["celery", "-A", "worker.main", "worker", "--loglevel=info", "--concurrency=4"]
