FROM postgres:16

# Install PostGIS from PGDG repo (already configured)
RUN apt-get update && \
    apt-get install -y --no-install-recommends postgresql-16-postgis-3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install TimescaleDB from PGDG repo
RUN apt-get update && \
    apt-get install -y --no-install-recommends postgresql-16-timescaledb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN echo "shared_preload_libraries = 'timescaledb'" >> /usr/share/postgresql/postgresql.conf.sample
